spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kamanote_tech?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: <PASSWORD>

upload:
  path: ${user.dir}/tmp/uploads # 指定上传文件的存储路径
  url-prefix: http://localhost:8080/images  # 访问上传文件的URL前缀
